---

- name: Installing and running apache 
  hosts: localhost

  tasks:
    - name: Installing apache 
      yum:
        name: httpd 
        state: present

    - name: start httpd
      service:
        name: httpd 
        state: started