---
- name: Downloafd tomcat from tomcat.apache.org
  hosts: websrvgrp
  become: true 

  tasks:
    - name: Create a directory /opt/tomcat 
      file:
        path: /opt/tomcat
        state: directory 
        mode: 0755
        owner: root
        group: root

    - name: Download tomcat using get_url
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
        dest: /opt/tomcat 
        mode: 0755
        group: ec2-user 
        owner: ec2-user